import React from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Routes, Route, Link, NavLink } from "react-router-dom";
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Menu, X, Plus, Sparkles } from "lucide-react";
import "./styles.css";

const game = { name:"Hening", status:"IN DEVELOPMENT", platform:"PLATFORM TBA", genre:["NARRATIVE","PSYCHOLOGICAL","EXPLORATION"], description:"A psychological narrative game about grief, memory, and the quiet spaces that hold us together. Some stories don't end when the credits roll." };
function Brand(){return <Link className="brand" to="/" aria-label="Nekolepon home"><img src="/nekolepon-logo.svg" alt="Nekolepon cat and klepon logo"/></Link>}
function Header(){const [open,setOpen]=React.useState(false);React.useEffect(()=>{document.body.classList.toggle("menu-open",open);return()=>document.body.classList.remove("menu-open")},[open]);const close=()=>setOpen(false);return <><div className="announcement"><span className="status-dot"/> INDEPENDENT GAME STUDIO <span className="announcement-right">MADE WITH FEELING, IN INDONESIA ↗</span></div><header className="site-header"><Brand/><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav className={"nav-links "+(open?"open":"")}><NavLink end to="/" onClick={close}>Home</NavLink><NavLink to="/studio" onClick={close}>About</NavLink><NavLink to="/games" onClick={close}>Games</NavLink><Link className="nav-cta" to="/contact" onClick={close}>Contact Us <ArrowUpRight size={14}/></Link></nav></header></>}
function Footer(){return <footer className="site-footer"><Brand/><span className="footer-note">MADE WITH A LITTLE EXTRA HEART. ♡</span><div className="footer-links"><Link to="/">HOME</Link><Link to="/studio">ABOUT</Link><Link to="/games">GAMES</Link><Link to="/contact">CONTACT US ↗</Link></div><span className="copyright">© NEKOLEPON {new Date().getFullYear()}</span></footer>}
function Eyebrow({children}){return <div className="eyebrow"><span className="eyebrow-icon">✳</span>{children}</div>}
function Ticker(){const items=<>PLAY WITH PURPOSE <b>✳</b> STORIES THAT STICK <b>✳</b> MADE WITH HEART <b>✳</b></>;return <div className="ticker" aria-label="Play with purpose. Stories that stick. Made with heart."><div className="ticker-track"><span className="ticker-group" aria-hidden="true">{items}</span><span className="ticker-group" aria-hidden="true">{items}</span></div></div>}
function MascotArt(){return <div className="hero-art"><div className="art-topline"><span>NEKO × KLEPON</span><span>FIG. 001</span></div><div className="sun-shape"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="spark spark-a">✳</span><span className="spark spark-b">✦</span><span className="spark spark-c">✳</span><img className="hero-mascot" src="/nekolepon-logo.svg" alt="Nekolepon cat klepon mascot"/><div className="art-caption"><span className="caption-stamp">MADE TO FEEL</span><span>OUR LITTLE<br/>POCKET UNIVERSE</span></div><div className="art-side-note">GOOD THINGS TAKE<br/>A LITTLE MAGIC.</div></div>}
function GameArtwork(){return <div className="game-art"><div className="game-art-grid"/><div className="game-logo">HENING<span>™</span></div><div className="window-scene"><div className="window-moon"/><div className="window-building building-a"/><div className="window-building building-b"/><div className="window-building building-c"/><div className="window-floor"/><div className="window-plant">♣</div></div><div className="game-art-label">A QUIET STORY ABOUT<br/>THE THINGS WE LEAVE BEHIND.</div><span className="corner-number">GAME NO. 001</span></div>}
function GameCard(){return <article className="game-card"><GameArtwork/><div className="game-info"><div className="game-info-top"><span className="pill">{game.status}</span><span className="game-year">{game.platform}</span></div><h3>{game.name}</h3><p>{game.description}</p><div className="game-tags">{game.genre.map(x=><span key={x}>{x}</span>)}</div><Link className="game-link" to="/games/hening">DISCOVER THE GAME <ArrowUpRight size={17}/></Link></div></article>}
function GamesSection(){return <section className="section games-section"><div className="section-heading"><div><Eyebrow>THE THINGS WE MAKE</Eyebrow><h2>Play, <span>please.</span></h2></div><p>Little worlds, big feelings.<br/>Here’s what we’re cooking up.</p></div><GameCard/><div className="coming-soon"><span className="coming-icon"><Plus/></span><div><strong>MORE WORLDS ARE BREWING.</strong><p>Good things take time. Stay curious.</p></div><span className="coming-index">NEXT UP / ???</span></div></section>}
function Recipe(){return <aside className="about-aside"><span>OUR RECIPE</span>{[["01","Curiosity","ASK THE ODD QUESTIONS."],["02","Craft","CARE ABOUT THE DETAILS."],["03","Heart","MAKE IT MEAN SOMETHING."]].map(([n,t,d])=><div className="recipe-item" key={n}><b>{n}</b><span>{t}<small>{d}</small></span></div>)}<div className="aside-doodle">n × k<br/><span>≋</span></div></aside>}
function AboutSection(){return <section className="about-section"><div className="about-doodle"><Sparkles/></div><div className="about-content"><Eyebrow>ABOUT NEKOLEPON</Eyebrow><h2>A small studio<br/>with <span>soft edges</span><br/>and big ideas.</h2><p className="about-copy">Nekolepon is an independent game studio from Indonesia. We bring together the curious spirit of a cat and the sweet little surprise of klepon to make games with character, warmth, and a point of view.</p><p className="about-copy">We believe games can be playful and profound. Weird and wonderful. A place to feel something real — even after you put the controller down.</p><Link className="button button-light" to="/studio">GET TO KNOW US <ArrowUpRight size={16}/></Link></div><Recipe/></section>}
function ContactBand(){return <section className="contact-section"><div className="contact-top"><Eyebrow>OPEN FOR GOOD CONVERSATIONS</Eyebrow><span className="contact-coordinate">MAKERS OF WORLDS / ID</span></div><h2>Got a good<br/><span>feeling?</span></h2><div className="contact-bottom"><p>Ideas, collaborations, kind words, or just to say hi. Our inbox is always open.</p><Link className="button button-dark contact-button" to="/contact">SAY HELLO <ArrowUpRight size={16}/></Link><span className="contact-star">✳</span></div></section>}
function Home(){return <main><section className="hero"><div className="hero-copy"><Eyebrow>TINY TEAM. UNTAMED IMAGINATION.</Eyebrow><h1>Games with<br/><span className="highlight-word">a little</span> <span className="outline-word">soul.</span></h1><p className="hero-description">We make worlds to get lost in, stories that stay with you, and games made with a whole lot of heart.</p><div className="hero-actions"><Link className="button button-dark" to="/games">EXPLORE OUR WORLDS <ArrowDownRight size={17}/></Link><Link className="text-link" to="/studio">A LITTLE ABOUT US <ArrowRight size={14}/></Link></div><div className="hero-footnote"><span className="scribble-arrow">↳</span> BUILT SLOWLY. FELT DEEPLY.</div></div><MascotArt/><div className="hero-bottom"><span>SCROLL TO WANDER <ArrowDown size={13}/></span><span className="hero-bottom-center">CREATIVITY, WITH A SIDE OF KLEPON.</span><span>01 / 04</span></div></section><Ticker/><GamesSection/><AboutSection/><ContactBand/></main>}
function GamesPage(){return <main className="inner-page"><Eyebrow>OUR LITTLE UNIVERSES</Eyebrow><h1>Made to <span>be felt.</span></h1><p className="inner-intro">Every game begins with a feeling. These are the worlds we’re bringing to life.</p><div className="inner-games"><GameCard/><div className="coming-soon"><span className="coming-icon"><Plus/></span><div><strong>MORE WORLDS ARE BREWING.</strong><p>Good things take time. Stay curious.</p></div></div></div></main>}
function HeningPage(){return <main className="inner-page game-detail"><Link className="back-link" to="/games">← ALL GAMES</Link><GameArtwork/><Eyebrow>{game.status}</Eyebrow><h1>Hening<span>™</span></h1><p className="inner-intro">{game.description}</p><div className="game-tags">{game.genre.map(x=><span key={x}>{x}</span>)}</div><p className="detail-note">A story still taking shape. More details coming when the time is right.</p><Link className="button button-dark" to="/contact">ASK US ABOUT HENING <ArrowUpRight size={16}/></Link></main>}
function StudioPage(){return <main><section className="inner-page studio-page"><Eyebrow>SMALL STUDIO, BIG FEELINGS</Eyebrow><h1>Soft edges.<br/><span>Big ideas.</span></h1><p className="inner-intro">Nekolepon is an independent game studio from Indonesia, inspired by the curious spirit of cats and the sweet little surprise of klepon.</p><p className="inner-copy">We make games that are playful and profound, weird and wonderful. We care about the tiny details, the moments between the big moments, and stories that follow you long after you put the controller down.</p><Recipe/></section><ContactBand/></main>}
function ContactPage(){return <main className="inner-page contact-page"><Eyebrow>OPEN FOR GOOD CONVERSATIONS</Eyebrow><h1>Let's make<br/><span>something.</span></h1><p className="inner-intro">Have an idea, want to collaborate, or just want to talk games? We'd love to hear from you.</p><a className="button button-dark email-button" href="mailto:hello@nekolepon.com?subject=Hello%20Nekolepon">HELLO@NEKOLEPON.COM <ArrowUpRight size={16}/></a><p className="contact-small">COLLABORATIONS · PRESS · KIND WORDS</p></main>}
function NotFound(){return <main className="inner-page"><Eyebrow>404 / LOST IN THE GRASS</Eyebrow><h1>Oops, <span>meow?</span></h1><p className="inner-intro">Looks like this little world doesn't exist yet.</p><Link className="button button-dark" to="/">BACK HOME <ArrowRight size={16}/></Link></main>}
function App(){React.useEffect(()=>{window.scrollTo(0,0)},[]);return <BrowserRouter><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/games" element={<GamesPage/>}/><Route path="/games/hening" element={<HeningPage/>}/><Route path="/studio" element={<StudioPage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/></BrowserRouter>}
createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);